# mqtt_host: str        = "127.0.0.1"
mqtt_host: str      = "mosquitto"
mqtt_port: int      = 1883
# db_host: str        = "127.0.0.1"
db_host: str        = "db"
db_port: int        = 5432
db_user: str        = "bp_user"
db_pass: str        = "bp_password"
db_dbname: str      = "bp"
debug: bool         = False