services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        volumes:
            - ./mosquitto:/mosquitto
        ports:
            - 1883:1883
            - 9001:9001

    db:
        image: postgres
        container_name: db_postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: bp_user
            POSTGRES_PASSWORD: bp_password
            POSTGRES_DB: bp
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/bp.sql:/docker-entrypoint-initdb.d/bp.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d 'user=bp_user dbname=bp password=bp_password'"]
            interval: 5s
            timeout: 5s
            retries: 5

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            - ADMINER_DESIGN=nette
    
    aggregator:
        build: 
            context: .
            dockerfile: ./aggregator/Dockerfile
        container_name: aggregator
        depends_on:
            db:
                condition: service_healthy
    
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        container_name: api
        ports:
            - 80:80
        depends_on:
            db:
                condition: service_healthy
